//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_chat_console
{
    using System;
    using System.Collections.Generic;
    
    public partial class mess
    {
        public int id_mess { get; set; }
        public string channel_name { get; set; }
        public string username { get; set; }
        public string content { get; set; }
    
        public virtual channel channel { get; set; }
    }
}
